name: Thought Police
favicon: null
layout_spectrum: 0.568754153791815
typography_spectrum: 0.80961
title: Thought Police
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191718'
    - '#534f50'
    - '#918f9a'
    - '#d5cac6'
  brandStrength: 0.5625
  lightness: 0.828405590262264
  saturation: 0.4243378199171275
  rhythmicContrast: 0.026723773451521993
purpose: []
