name: Thought Police
favicon: null
layout_spectrum: 0.26238
typography_spectrum: 0.52248
title: Thought Police
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191718'
    - '#534f50'
    - '#918f9a'
    - '#d5cac6'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
